spring:
  application:
    name: blog-service

  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password

  #jpa
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'

  #Kafka
  kafka:
    bootstrap-servers: url
    consumer:
      group-id: blog-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  #security
  profiles:
    include: secret
